version: '3'

services:

  recorder:
    build:
      context: .
      args:
         recorder_version: 0.8.3
    container_name: recorder
    image: owntracks/recorder

  otrecorder:
    image: owntracks/recorder
    ports:
      - 8083:8083
    volumes:
      - config:/config
      - store:/store
    restart: unless-stopped

volumes:
  store:
  config:

